### ISSUE TITLE
Registration an Login Page 

### ISSUE THREAD

**Issue by Philiswa-M** [iam-hbk/pave#18]
@KenanK0 , @iam-hbk .
The Registration and login view password icons work vice versa. 
When you set the icon to not show the password, the password shows and vice versa

**Comment by iam-hbk** [comment]
So this was my thinking:
When the eye is open, the password should be hidden so that it hints to user to "reveal" it 
And when the password is visible, the icon is a closed eye so that it hints the user to hide the password 

Is this not how it is implemented?

**Comment by Philiswa-M** [comment]
Okay I get you. My logic was off. 
no problem, will close the issue
