### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by Philiswa-M** [iam-hbk/pave#6]
The UI of the Registration page needs to be fixed. 
The labels overlap one another upon clicking on the different fields

**Comment by iam-hbk** [comment]
On it, I didn't test on different devices

**Comment by KenanK0** [comment]
this issue only happens on android device

**Comment by iam-hbk** [comment]
@Philiswa-M please checkout #8  for the fix of this issue and close it if you think it has been solved
